name: Run new-release script

on:
  repository_dispatch:
    types: [publish]

jobs:
  generate_diffs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: yarn deps install
        run: yarn install

      - name: Run new-release script
        run: ./scripts/new-release.sh ${{ github.event.client_payload.version }}
