name: Send notifications when a new release is published

on:
  push:
    branches:
      - master

jobs:
  release_notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: yarn install
      - name: Notify upgrade-support of a new release
        run: ./scripts/notify-new-release.js ${{ secrets.SPECIAL_GITHUB_TOKEN }}
